version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing dependencies...
      - npm ci
  build:
    commands:
      - echo Running tests...
      - echo Tests started on `date`
      - whoami
      - docker build -t migrate-mysql -f src/__test__/docker/migrate-mysql.dockerfile .
      - docker-compose -f src/__test__/docker/docker-compose.yml up -d
      - npm run test
  post_build:
    commands:
      - echo Tests completed on `date`

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - '/root/.npm/**/*'