version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing dependencies...
      - npm ci
  build:
    commands:
      - echo Running tests...
      - echo Tests started on `date`
      - npm run test
  post_build:
    commands:
      - echo Tests completed on `date`

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - '/root/.npm/**/*'