version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - echo Installing dependencies...
      - npm ci
  build:
    commands:
      - echo Building project...
      - echo Build started on `date`
      - npm run build
  test:
    commands:
      - npm run test

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - '/root/.npm/**/*'