import {MigrationInterface, QueryRunner} from "typeorm";

export class UpdateApplicationStatusDescriptions1645049379167 implements MigrationInterface {
    name = 'UpdateApplicationStatusDescriptions1645049379167'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'Estado inicial de cualquier solicitud, se crea en pendiente mientras se inicializan los procesos correspondientes.', ordenEstados = 1 WHERE idEstadoSolicitud = 1;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 0, visibleParaPartners = 0, descripcion = '[DEPRECTAED] Se autenticó la solicitud terminada mediante el ingreso correcto del NIP enviado al celular de usuario.', ordenEstados = NULL WHERE idEstadoSolicitud = 2;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 0, visibleParaPartners = 0, descripcion = '[DEPRECTAED] Aun no se autenticó la solicitud terminada, usuario debe ingresar NIP correcto enviado a su celular.', ordenEstados = NULL WHERE idEstadoSolicitud = 3;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 0, visibleParaPartners = 0, descripcion = '[DEPRECTAED] Solicitud fue autenticada pero esta a la espera de alguna decisión opertiva.', ordenEstados = NULL WHERE idEstadoSolicitud = 6;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'La solicitud fue creada exitosamente.', ordenEstados = 2 WHERE idEstadoSolicitud = 20;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'El usuario completo el primer paso del formulario.', ordenEstados = 3 WHERE idEstadoSolicitud = 21;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'El usuario completo el segundo paso del formulario.', ordenEstados = 4 WHERE idEstadoSolicitud = 22;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'El usuario completo el tercer paso del formulario.', ordenEstados = 5 WHERE idEstadoSolicitud = 23;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'El usuario completo el cuarto paso del formulario.', ordenEstados = 6 WHERE idEstadoSolicitud = 24;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'El usuario completo el quinto paso del formulario.', ordenEstados = 7 WHERE idEstadoSolicitud = 25;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'Se validaron todos los pasos del formulario exitosamente.', ordenEstados = 8 WHERE idEstadoSolicitud = 26;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 0, visibleParaPartners = 0, descripcion = '[DEPRECATED] Necesitamos verificar la información del cliente y le haremos una llamada para corroborar algunos datos.', ordenEstados = NULL WHERE idEstadoSolicitud = 12;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 1, descripcion = 'Nuestro equipo está preparando una oferta con su monto máximo autorizado y su contrato digital.', ordenEstados = 9 WHERE idEstadoSolicitud = 8;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'Este estado sucede cuando se requiere info extra del solicitante.', ordenEstados = 10 WHERE idEstadoSolicitud = 16;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 1, descripcion = 'El cliente está pre-autorizado, pero aún no ha subidos sus documentos en nuestra plataforma. Le enviamos correo con el link a la plataforma para subir documentos. Te recomendamos contactarlo para que continúe el proceso y puedas cerrar la venta.', ordenEstados = 11 WHERE idEstadoSolicitud = 4;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 1, descripcion = 'Nuestro equipo se encuentra verificando los documentos proporcionados por el cliente, pero aún hay documentos que el cliente no ha enviado.', ordenEstados = 12 WHERE idEstadoSolicitud = 11;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 1, descripcion = 'Nuestro equipo se encuentra verificando los documentos proporcionados por el cliente.', ordenEstados = 13 WHERE idEstadoSolicitud = 10;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'Los documentos fueron aprobados.', ordenEstados = 14 WHERE idEstadoSolicitud = 27;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 1, descripcion = 'Ya le enviamos su oferta y contrato digital, pero no lo ha firmado. La firma es digital, lo hace entrando a la página de la oferta que le enviamos al correo al cliente. Te recomendamos contactarlo para que continúe el proceso y puedas cerrar la venta.', ordenEstados = 15 WHERE idEstadoSolicitud = 7;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 1, descripcion = 'El crédito ha sido autorizado ya podemos entregarle su compra por el monto autorizado.', ordenEstados = 16 WHERE idEstadoSolicitud = 9;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'El usuario firmó su contrato pero estamos esperando el pago de su enganche para autorizar el crédito.', ordenEstados = 17 WHERE idEstadoSolicitud = 28;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'El crédito pasó por todas las etapas de la firma, está activo y autorizado.', ordenEstados = 18 WHERE idEstadoSolicitud = 29;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'Partners marcaron que el producto o la compra ya fue entregado de su lado.', ordenEstados = 19 WHERE idEstadoSolicitud = 18;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'Dinero fue desembolsado por parte de Atrato hacia merchant.', ordenEstados = 20 WHERE idEstadoSolicitud = 19;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'Cliente no autorizado para crédito y rechazado.', ordenEstados = 50 WHERE idEstadoSolicitud = 5;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'Cliente no autorizado para crédito y rechazado automáticamente por modelos.', ordenEstados = 51 WHERE idEstadoSolicitud = 13;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'Cuando el comercio o solicitante tiene alguna queja y el proceso está avanzado ya, entra en disputa.', ordenEstados = 52 WHERE idEstadoSolicitud = 17;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'La solicitud fue cancelada manualmente por razón ajena a atrato.', ordenEstados = 53 WHERE idEstadoSolicitud = 15;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'La solicitud fue caducada por inactividad del usuario por más de 15 días.', ordenEstados = 54 WHERE idEstadoSolicitud = 14;`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'Estado inicial de cualquier solicitud, se crea en pendiente mientras se inicializan los procesos correspondientes.', ordenEstados = NULL WHERE idEstadoSolicitud = 1;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'Se autenticó la solicitud terminada mediante el ingreso correcto del NIP enviado al celular de usuario.', ordenEstados = NULL WHERE idEstadoSolicitud = 2;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'Aun no se autenticó la solicitud terminada, usuario debe ingresar NIP correcto enviado a su celular.', ordenEstados = NULL WHERE idEstadoSolicitud = 3;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'Solicitud fue autenticada pero esta a la espera de alguna decisión opertiva.', ordenEstados = NULL WHERE idEstadoSolicitud = 6;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'La solicitud fue creada exitosamente.', ordenEstados = NULL WHERE idEstadoSolicitud = 20;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'El usuario completo el primer paso del formulario.', ordenEstados = NULL WHERE idEstadoSolicitud = 21;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'El usuario completo el segundo paso del formulario.', ordenEstados = NULL WHERE idEstadoSolicitud = 22;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'El usuario completo el tercer paso del formulario.', ordenEstados = NULL WHERE idEstadoSolicitud = 23;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'El usuario completo el cuarto paso del formulario.', ordenEstados = NULL WHERE idEstadoSolicitud = 24;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 1, descripcion = 'El usuario completo el quinto paso del formulario.', ordenEstados = NULL WHERE idEstadoSolicitud = 25;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'Se validaron todos los pasos del formulario exitosamente.', ordenEstados = NULL WHERE idEstadoSolicitud = 26;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 1, descripcion = 'Necesitamos verificar la información del cliente y le haremos una llamada para corroborar algunos datos.', ordenEstados = NULL WHERE idEstadoSolicitud = 12;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 1, descripcion = 'Nuestro equipo está preparando una oferta con su monto máximo autorizado y su contrato digital.', ordenEstados = NULL WHERE idEstadoSolicitud = 8;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'Este estado sucede cuando se requiere info extra del solicitante.', ordenEstados = NULL WHERE idEstadoSolicitud = 16;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 1, descripcion = 'El cliente está pre-autorizado, pero aún no ha subidos sus documentos en nuestra plataforma. Le enviamos correo con el link a la plataforma para subir documentos. Te recomendamos contactarlo para que continúe el proceso y puedas cerrar la venta.', ordenEstados = NULL WHERE idEstadoSolicitud = 4;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 1, descripcion = 'Nuestro equipo se encuentra verificando los documentos proporcionados por el cliente, pero aún hay documentos que el cliente no ha enviado.', ordenEstados = NULL WHERE idEstadoSolicitud = 11;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 1, descripcion = 'Nuestro equipo se encuentra verificando los documentos proporcionados por el cliente.', ordenEstados = NULL WHERE idEstadoSolicitud = 10;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 1, descripcion = 'Nuestro equipo se encuentra verificando los documentos proporcionados por el cliente.', ordenEstados = NULL WHERE idEstadoSolicitud = 10;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'Los documentos fueron aprobados.', ordenEstados = NULL WHERE idEstadoSolicitud = 27;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 1, descripcion = 'Ya le enviamos su oferta y contrato digital, pero no lo ha firmado. La firma es digital, lo hace entrando a la página de la oferta que le enviamos al correo al cliente. Te recomendamos contactarlo para que continúe el proceso y puedas cerrar la venta.', ordenEstados = NULL WHERE idEstadoSolicitud = 7;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 1, descripcion = 'El crédito ha sido autorizado ya podemos entregarle su compra por el monto autorizado.', ordenEstados = NULL WHERE idEstadoSolicitud = 9;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'El usuario firmó su contrato pero estamos esperando el pago de su enganche para autorizar el crédito.', ordenEstados = NULL WHERE idEstadoSolicitud = 28;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'El crédito pasó por todas las etapas de la firma, está activo y autorizado.', ordenEstados = NULL WHERE idEstadoSolicitud = 29;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'Partners marcaron que el producto o la compra ya fue entregado de su lado.', ordenEstados = NULL WHERE idEstadoSolicitud = 18;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'Dinero fue desembolsado por parte de Atrato hacia merchant.', ordenEstados = NULL WHERE idEstadoSolicitud = 19;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'Cliente no autorizado para crédito y rechazado.', ordenEstados = NULL WHERE idEstadoSolicitud = 5;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'Cliente no autorizado para crédito y rechazado automáticamente por modelos.', ordenEstados = NULL WHERE idEstadoSolicitud = 13;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'Cuando el comercio o solicitante tiene alguna queja y el proceso está avanzado ya, entra en disputa.', ordenEstados = NULL WHERE idEstadoSolicitud = 17;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'La solicitud fue cancelada manualmente por razón ajena a atrato.', ordenEstados = NULL WHERE idEstadoSolicitud = 15;`);
        await queryRunner.query(`UPDATE staticEstadosSolicitudes SET activo = 1, visibleParaPartners = 0, descripcion = 'La solicitud fue caducada por inactividad del usuario por más de 15 días.', ordenEstados = NULL WHERE idEstadoSolicitud = 14;`);
    }

}
