version: '3'

services:
  migrate:
    command: echo insert-migrations-here! && ./wait-for-it.sh db:3306 -- cd db && echo insert-migrations-here!
    volumes:
      - ./target:/opt/setup/target
    image: migrate-mysql
    build:
      context: ../../
      dockerfile: src/__test__/docker/migrate-mysql.dockerfile
    depends_on:
      - "db"

  db:
    image: mysql:8.0.30
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    restart: on-failure
