pipeline{
    agent any

    tools { nodejs "14.17.6", docker "default-docker" }

    stages {
    stage('Test npm') {
      steps {
        sh """
          npm --version
        """
      }
    }
    stage('Install dependencies') { // for display purposes
        steps{
            sh "npm ci"
        }
    }

    stage('Build docker image'){
        steps{
            sh "docker build -t migrate-mysql -f src/__test__/docker/migrate-mysql.dockerfile ."
        }
    }
    stage('Docker compose'){
        steps{
            sh "docker-compose -f src/__test__/docker/docker-compose.yml up -d"
        }
    }
   stage('Tests') { // for display purposes
       steps{
            sh "npm run test"
        }
    }
    stage('Build') { // for display purposes
        steps{
            sh "npm run build"
        }
    }
   stage('QA env') { // for display purposes
        steps{
            echo "Quality ensured :)"
        }
    }
   stage('Deploy') { // for display purposes
        steps{
            echo "Awseom code has been deployed!"
        }
    }

    }
    post{
        always{
            echo "This will always run"
        }
        success {
            echo "This will run on success!"
        }
        failure{
            echo "This will run in failure"
        }
        unstable{
            echo "This will run only if run was marked as unstable"
        }
        changed{
            echo "This will only run if the state of the pipeline has changed"
        }
    }
}