name: DB tests
on: [push]
jobs:
  integration-tests:
    name: Running DB Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: nwtwork
        run: |
          docker network create samplenetwork

      - name: Build image
        id: build-image
        run: |
          # Build a docker container
          docker build -t migrate-mysql -f src/__test__/docker/migrate-mysql.dockerfile .

      - name: 'docker/compose:1.19.0'
        id: compose-up
        run: |
          docker-compose -f src/__test__/docker/docker-compose.yml up -d

      - name: Install packages
        run: npm ci
      - name: DB tests
        run: npm run test:unit
          - env: 'MYSQL_HOST=db'

