name: Integration tests
on: [push]
jobs:
  eslint:
    name: Running Integration tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: npm ci
      - name: Unit tests
        run: npm run test:inegration